/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as SuiviRouteImport } from './routes/suivi'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CommanderRouteImport } from './routes/commander'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackCodeRouteImport } from './routes/track.$code'
import { Route as AuthenticatedSuiviLivreursRouteImport } from './routes/_authenticated/suivi-livreurs'
import { Route as AuthenticatedServiceClientRouteImport } from './routes/_authenticated/service-client'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedPrintBordereauxRouteImport } from './routes/_authenticated/print-bordereaux'
import { Route as AuthenticatedOperationsRouteImport } from './routes/_authenticated/operations'
import { Route as AuthenticatedMesRetoursRouteImport } from './routes/_authenticated/mes-retours'
import { Route as AuthenticatedMesColisRouteImport } from './routes/_authenticated/mes-colis'
import { Route as AuthenticatedLivreurRouteImport } from './routes/_authenticated/livreur'
import { Route as AuthenticatedFeuilleDeRouteRouteImport } from './routes/_authenticated/feuille-de-route'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as AuthenticatedCommercialRouteImport } from './routes/_authenticated/commercial'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedColisTrackingRouteImport } from './routes/_authenticated/colis.$tracking'

const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const SuiviRoute = SuiviRouteImport.update({
  id: '/suivi',
  path: '/suivi',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CommanderRoute = CommanderRouteImport.update({
  id: '/commander',
  path: '/commander',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackCodeRoute = TrackCodeRouteImport.update({
  id: '/track/$code',
  path: '/track/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSuiviLivreursRoute =
  AuthenticatedSuiviLivreursRouteImport.update({
    id: '/suivi-livreurs',
    path: '/suivi-livreurs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedServiceClientRoute =
  AuthenticatedServiceClientRouteImport.update({
    id: '/service-client',
    path: '/service-client',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPrintBordereauxRoute =
  AuthenticatedPrintBordereauxRouteImport.update({
    id: '/print-bordereaux',
    path: '/print-bordereaux',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOperationsRoute = AuthenticatedOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMesRetoursRoute = AuthenticatedMesRetoursRouteImport.update({
  id: '/mes-retours',
  path: '/mes-retours',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMesColisRoute = AuthenticatedMesColisRouteImport.update({
  id: '/mes-colis',
  path: '/mes-colis',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLivreurRoute = AuthenticatedLivreurRouteImport.update({
  id: '/livreur',
  path: '/livreur',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFeuilleDeRouteRoute =
  AuthenticatedFeuilleDeRouteRouteImport.update({
    id: '/feuille-de-route',
    path: '/feuille-de-route',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCommercialRoute = AuthenticatedCommercialRouteImport.update({
  id: '/commercial',
  path: '/commercial',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedColisTrackingRoute =
  AuthenticatedColisTrackingRouteImport.update({
    id: '/colis/$tracking',
    path: '/colis/$tracking',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/commander': typeof CommanderRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/suivi': typeof SuiviRoute
  '/tarifs': typeof TarifsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/commercial': typeof AuthenticatedCommercialRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/feuille-de-route': typeof AuthenticatedFeuilleDeRouteRoute
  '/livreur': typeof AuthenticatedLivreurRoute
  '/mes-colis': typeof AuthenticatedMesColisRoute
  '/mes-retours': typeof AuthenticatedMesRetoursRoute
  '/operations': typeof AuthenticatedOperationsRoute
  '/print-bordereaux': typeof AuthenticatedPrintBordereauxRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/service-client': typeof AuthenticatedServiceClientRoute
  '/suivi-livreurs': typeof AuthenticatedSuiviLivreursRoute
  '/track/$code': typeof TrackCodeRoute
  '/colis/$tracking': typeof AuthenticatedColisTrackingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/commander': typeof CommanderRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/suivi': typeof SuiviRoute
  '/tarifs': typeof TarifsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/commercial': typeof AuthenticatedCommercialRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/feuille-de-route': typeof AuthenticatedFeuilleDeRouteRoute
  '/livreur': typeof AuthenticatedLivreurRoute
  '/mes-colis': typeof AuthenticatedMesColisRoute
  '/mes-retours': typeof AuthenticatedMesRetoursRoute
  '/operations': typeof AuthenticatedOperationsRoute
  '/print-bordereaux': typeof AuthenticatedPrintBordereauxRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/service-client': typeof AuthenticatedServiceClientRoute
  '/suivi-livreurs': typeof AuthenticatedSuiviLivreursRoute
  '/track/$code': typeof TrackCodeRoute
  '/colis/$tracking': typeof AuthenticatedColisTrackingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/commander': typeof CommanderRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/suivi': typeof SuiviRoute
  '/tarifs': typeof TarifsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/commercial': typeof AuthenticatedCommercialRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/feuille-de-route': typeof AuthenticatedFeuilleDeRouteRoute
  '/_authenticated/livreur': typeof AuthenticatedLivreurRoute
  '/_authenticated/mes-colis': typeof AuthenticatedMesColisRoute
  '/_authenticated/mes-retours': typeof AuthenticatedMesRetoursRoute
  '/_authenticated/operations': typeof AuthenticatedOperationsRoute
  '/_authenticated/print-bordereaux': typeof AuthenticatedPrintBordereauxRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/service-client': typeof AuthenticatedServiceClientRoute
  '/_authenticated/suivi-livreurs': typeof AuthenticatedSuiviLivreursRoute
  '/track/$code': typeof TrackCodeRoute
  '/_authenticated/colis/$tracking': typeof AuthenticatedColisTrackingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/commander'
    | '/login'
    | '/signup'
    | '/suivi'
    | '/tarifs'
    | '/admin'
    | '/commercial'
    | '/equipe'
    | '/feuille-de-route'
    | '/livreur'
    | '/mes-colis'
    | '/mes-retours'
    | '/operations'
    | '/print-bordereaux'
    | '/profil'
    | '/service-client'
    | '/suivi-livreurs'
    | '/track/$code'
    | '/colis/$tracking'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/commander'
    | '/login'
    | '/signup'
    | '/suivi'
    | '/tarifs'
    | '/admin'
    | '/commercial'
    | '/equipe'
    | '/feuille-de-route'
    | '/livreur'
    | '/mes-colis'
    | '/mes-retours'
    | '/operations'
    | '/print-bordereaux'
    | '/profil'
    | '/service-client'
    | '/suivi-livreurs'
    | '/track/$code'
    | '/colis/$tracking'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/commander'
    | '/login'
    | '/signup'
    | '/suivi'
    | '/tarifs'
    | '/_authenticated/admin'
    | '/_authenticated/commercial'
    | '/_authenticated/equipe'
    | '/_authenticated/feuille-de-route'
    | '/_authenticated/livreur'
    | '/_authenticated/mes-colis'
    | '/_authenticated/mes-retours'
    | '/_authenticated/operations'
    | '/_authenticated/print-bordereaux'
    | '/_authenticated/profil'
    | '/_authenticated/service-client'
    | '/_authenticated/suivi-livreurs'
    | '/track/$code'
    | '/_authenticated/colis/$tracking'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CommanderRoute: typeof CommanderRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SuiviRoute: typeof SuiviRoute
  TarifsRoute: typeof TarifsRoute
  TrackCodeRoute: typeof TrackCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suivi': {
      id: '/suivi'
      path: '/suivi'
      fullPath: '/suivi'
      preLoaderRoute: typeof SuiviRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commander': {
      id: '/commander'
      path: '/commander'
      fullPath: '/commander'
      preLoaderRoute: typeof CommanderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$code': {
      id: '/track/$code'
      path: '/track/$code'
      fullPath: '/track/$code'
      preLoaderRoute: typeof TrackCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/suivi-livreurs': {
      id: '/_authenticated/suivi-livreurs'
      path: '/suivi-livreurs'
      fullPath: '/suivi-livreurs'
      preLoaderRoute: typeof AuthenticatedSuiviLivreursRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/service-client': {
      id: '/_authenticated/service-client'
      path: '/service-client'
      fullPath: '/service-client'
      preLoaderRoute: typeof AuthenticatedServiceClientRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/print-bordereaux': {
      id: '/_authenticated/print-bordereaux'
      path: '/print-bordereaux'
      fullPath: '/print-bordereaux'
      preLoaderRoute: typeof AuthenticatedPrintBordereauxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/operations': {
      id: '/_authenticated/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof AuthenticatedOperationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mes-retours': {
      id: '/_authenticated/mes-retours'
      path: '/mes-retours'
      fullPath: '/mes-retours'
      preLoaderRoute: typeof AuthenticatedMesRetoursRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mes-colis': {
      id: '/_authenticated/mes-colis'
      path: '/mes-colis'
      fullPath: '/mes-colis'
      preLoaderRoute: typeof AuthenticatedMesColisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/livreur': {
      id: '/_authenticated/livreur'
      path: '/livreur'
      fullPath: '/livreur'
      preLoaderRoute: typeof AuthenticatedLivreurRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feuille-de-route': {
      id: '/_authenticated/feuille-de-route'
      path: '/feuille-de-route'
      fullPath: '/feuille-de-route'
      preLoaderRoute: typeof AuthenticatedFeuilleDeRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/commercial': {
      id: '/_authenticated/commercial'
      path: '/commercial'
      fullPath: '/commercial'
      preLoaderRoute: typeof AuthenticatedCommercialRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/colis/$tracking': {
      id: '/_authenticated/colis/$tracking'
      path: '/colis/$tracking'
      fullPath: '/colis/$tracking'
      preLoaderRoute: typeof AuthenticatedColisTrackingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCommercialRoute: typeof AuthenticatedCommercialRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedFeuilleDeRouteRoute: typeof AuthenticatedFeuilleDeRouteRoute
  AuthenticatedLivreurRoute: typeof AuthenticatedLivreurRoute
  AuthenticatedMesColisRoute: typeof AuthenticatedMesColisRoute
  AuthenticatedMesRetoursRoute: typeof AuthenticatedMesRetoursRoute
  AuthenticatedOperationsRoute: typeof AuthenticatedOperationsRoute
  AuthenticatedPrintBordereauxRoute: typeof AuthenticatedPrintBordereauxRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedServiceClientRoute: typeof AuthenticatedServiceClientRoute
  AuthenticatedSuiviLivreursRoute: typeof AuthenticatedSuiviLivreursRoute
  AuthenticatedColisTrackingRoute: typeof AuthenticatedColisTrackingRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCommercialRoute: AuthenticatedCommercialRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedFeuilleDeRouteRoute: AuthenticatedFeuilleDeRouteRoute,
  AuthenticatedLivreurRoute: AuthenticatedLivreurRoute,
  AuthenticatedMesColisRoute: AuthenticatedMesColisRoute,
  AuthenticatedMesRetoursRoute: AuthenticatedMesRetoursRoute,
  AuthenticatedOperationsRoute: AuthenticatedOperationsRoute,
  AuthenticatedPrintBordereauxRoute: AuthenticatedPrintBordereauxRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedServiceClientRoute: AuthenticatedServiceClientRoute,
  AuthenticatedSuiviLivreursRoute: AuthenticatedSuiviLivreursRoute,
  AuthenticatedColisTrackingRoute: AuthenticatedColisTrackingRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CommanderRoute: CommanderRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SuiviRoute: SuiviRoute,
  TarifsRoute: TarifsRoute,
  TrackCodeRoute: TrackCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
